version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: campus_portal_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: campus_portal
    volumes:
      - mongodb_data:/data/db
    networks:
      - campus-network

  backend:
    build: ./backend
    container_name: campus_portal_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/campus_portal
      - JWT_SECRET=campus_portal_secret_key_2024_do_not_use_in_production
      - PORT=5000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - campus-network
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: campus_portal_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - campus-network
    stdin_open: true
    tty: true

volumes:
  mongodb_data:

networks:
  campus-network:
    driver: bridge
